//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransectionItem
    {
        public int id { get; set; }
        public int transectionId { get; set; }
        public int productId { get; set; }
        public int quantity { get; set; }
        public int priceAtSale { get; set; }
        public int CurrencyIdAtSale { get; set; }
        public int stateId { get; set; }
        public string Comment { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Transection Transection { get; set; }
        public virtual TransectionItemStatu TransectionItemStatu { get; set; }
    }
}
